### ISSUE TITLE
Refresh access token?

### ISSUE THREAD

**Issue by angelxmoreno** [jkutianski/meetup-api#16]
How can I refresh an access token? I check on each request whether the TTL is done but I do not see in the docs how to refresh the token once it expires.

**Comment by jkutianski** [comment]
Are you talking about OAuth token?

**Comment by angelxmoreno** [comment]
No, I am referring to http://www.meetup.com/meetup_api/auth/#oauth2-refresh

**Comment by jkutianski** [comment]
Thanks for pointing this! I will implement it ASAP!

**Comment by jkutianski** [comment]
Added Oauth2 support on https://github.com/jkutianski/meetup-api/commit/731ca77716b22b8d77118d9e6f5c2569feeb2f90

New functions:

```Javascript
meetup.getOAuth2RequestToken(params, callback);

meetup.getOAuth2AccessToken(oauth_verifier, callback);

meetup.refreshOAuth2AccessToken(refresh_token, callback);
```

**Comment by angelxmoreno** [comment]
geez! `I will implement it ASAP` is usually not the response I expect nor it being done in a matter of hours! YOU ROCK!

**Comment by jkutianski** [comment]
@angelxmoreno Well... isn't the most clean code!
