### ISSUE TITLE
Timeout error when deploying the client behind corporate proxy

### ISSUE THREAD

**Issue by MustafaDasorwala** [jkutianski/meetup-api#19]
Getting the following error when deploying the client behind corporate proxy

 { [Error: connect ETIMEDOUT 104.16.85.48:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.16.85.48',
  port: 443,
  response: undefined }

**Comment by jkutianski** [comment]
I guess it's not a transparent proxy. No?
The proxy routine isn't implemented yet. Give me some days.

**Comment by jkutianski** [comment]
The commit https://github.com/jkutianski/meetup-api/commit/f84e56cb39d426dbe516cbdeabbe8484d7e4fe3a adds support to proxy client but has issues with HTTP(S) enpoints (https://github.com/jkutianski/meetup-api/issues/20). I don't know yet if is something related to the https-proxy-agent module or to CloudFlare service.
With Websockets works fine.

**Comment by jkutianski** [comment]
@MustafaDasorwala I close this. Please comment on the https://github.com/jkutianski/meetup-api/issues/20 issue is you've the same problem.
