### ISSUE TITLE
How do I retrieve Meetup members calendar events? (Question)

### ISSUE THREAD

**Issue by jasan-s** [jkutianski/meetup-api#21]
I wanted to integrate meetup api with my app but I can't seem to figure out how to GET users I'm going events.

**Comment by jkutianski** [comment]
I'm not sure if I catch your question, but if you are trying to get the RSVPs of an specific event you can use `getRSVPs()`.
For example for this event https://www.meetup.com/es-ES/banodejs/events/237407547/ you can use this
```
meetup.getRSVPs({
    event_id: 237407547,
    urlname: 'banodejs'
}, function(err, resp) {
    if (err) {
        console.error('Found meetup error', err);
    }
    console.log(JSON.stringify(resp, null, 2));
});
```
