### ISSUE TITLE
CERT_NOT_YET_VALID error - rate limit surpassed?

### ISSUE THREAD

**Issue by soosap** [jkutianski/meetup-api#22]
Hi there,

I am using your library like below. It did work for a while. But now I am receiving this error. Does it mean I surpassed the rate limit?

```js
meetup.getEvent({ urlname: 'ReactStuttgart', id: req.params.id }, (error, event) => {
  if (error) {
    console.log(error);
    res.send(error);
  } else {
    console.log(`Event: ${req.params.id} fetched!`);
    res.json(event);
  }
});
```

```
{ Error: certificate is not yet valid
  at TLSSocket.<anonymous> (_tls_wrap.js:1079:38)
  at emitNone (events.js:86:13)
  at TLSSocket.emit (events.js:185:7)
  at TLSSocket._finishInit (_tls_wrap.js:603:8)
  at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38) code: 'CERT_NOT_YET_VALID', response: undefined }
```

**Comment by soosap** [comment]
Seems to be related to meetup's recent AWS move. Can you advise whether there is a quickfix?

https://medium.com/meetup/moving-meetup-to-the-cloud-9908db0e4781#.z1f3rfqu7
https://groups.google.com/forum/#!forum/meetup-api

**Comment by soosap** [comment]
Hmm, I restarted...closed all processes and restarted. It suddenly started working again. Sorry for the noise.

**Comment by jkutianski** [comment]
Good to know! I've some problems with the tests on the last week too. Look like they've some problems with the migration.

**Comment by jkutianski** [comment]
If you continúe with some of this problems try to generate a new oauth secret and/or a new API token.
