### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by randallagordon** [jkutianski/meetup-api#23]
On a project using `meetup-api`, we're occasionally seeing a `SyntaxError: Unexpected end of JSON input` error from [line 367](https://github.com/jkutianski/meetup-api/blob/68048b708aa9268e11f68ff9fee455761e8d8c74/lib/meetup.js#L367) since the `JSON.parse` isn't wrapped in a `try/catch`.

I'm happy to open a PR to add it in, but I was also curious if you might have some insight into how/when this would occur with a Meetup response?

**Comment by jkutianski** [comment]
I change a little bit your code.
Are you checking the `ratelimit` object on the response?

**Comment by randallagordon** [comment]
Whoops, that was an unintended side effect! I was too narrowly focused on what that one line alone was doing and missed how it'd goof up attaching the `ratelimit` stuff.

**Comment by jkutianski** [comment]
Ahhh I did a bad job trying to express my intentions in that question. I am sorry!
I'm not complaining about it, just point the most probable cause for this behavior.
> I was also curious if you might have some insight into how/when this would occur with a Meetup response?
With this change  https://github.com/jkutianski/meetup-api/commit/265db287e078be4d523fe7e95890d52c39d3a645 you can check the `ratelimit` on the response.

**Comment by randallagordon** [comment]
Oh! I've got ya now. With the `try/catch` in place along with your tweaks, we'll be able to successfully log the error and response with the `ratelimit` data and find out if it is the cause.

**Comment by chrisforrette** [comment]
Hi @jkutianski! I'm working with @randallagordon on this and we're still experiencing an `Unexpected end of JSON input` error from time to time that we're trying to figure out. We were thinking it would be super helpful to get the raw response attached to the error object—so changing this:

https://github.com/jkutianski/meetup-api/blob/master/lib/meetup.js#L372

to this:

```js
err = error
err.response = res
```

Is that acceptable to you if I open a PR for it?

**Comment by jkutianski** [comment]
Shure.
Tell me if you found the problem.

**Comment by jkutianski** [comment]
any news about this?

**Comment by randallagordon** [comment]
We've not seen the error in 23 days at this point, so no news yet. One of those rare situations where you'd actually like an error to pop up once & a while! :)

However, I'm noting that PR #25 may have not been published to npm? Looks like the latest version, 1.4.12, was published on April 20th and that PR was merged on May 2nd.

**Comment by jkutianski** [comment]
Done!

**Comment by randallagordon** [comment]
Awesome, thanks! We'll get upgraded shortly and, so long as the error does pop up again, let you know what we find.

**Comment by jkutianski** [comment]
Ok. I'm closing this issue. If the error appears again feel free to open it again.
