### ISSUE TITLE
must be a member of banodejs meetup for tests to pass

### ISSUE THREAD

**Issue by pfhawkins** [jkutianski/meetup-api#29]
If you aren't a member of https://www.meetup.com/banodejs/ the getEvent test will fail with this error:

`AssertionError [ERR_ASSERTION]: Method getEvent don't return the "status" key`

**Comment by jkutianski** [comment]
Sorry for the long long delay. Yes I know but you've to be member of a group all the calls. You can change it on the JSON https://github.com/jkutianski/meetup-api/blob/master/lib/endpoints.json
