### ISSUE TITLE
Searching groups

### ISSUE THREAD

**Issue by ExAmbitionAl** [jkutianski/meetup-api#33]
Is there a method to get array of groups in the same region? I want to present to my users list of 10 trending groups from city and category that they type in text box.

**Comment by jkutianski** [comment]
You can use `findGroups()`

```
meetup.findGroups({
	location: 'Buenos Aires', // or lat & lon
	page: 10,
	category: 34
}, function (err, results) {
    console.log(results);
});
```

https://www.meetup.com/es-ES/meetup_api/docs/find/groups/?uri=%2Fmeetup_api%2Fdocs%2Ffind%2Fgroups%2F

Take on mind that the response isn't an Array but an Object.
