### ISSUE TITLE
getUpcomingEvents with topic_category?

### ISSUE THREAD

**Issue by romshiri** [jkutianski/meetup-api#34]
Hi, it's not necessarily related to this library as I'm not able to make it work in MeetupAPI console as well, but perhaps someone here can help.   

I'm trying to use the 'upcmoingEvents' endpoint with a topic filter using the "topic_category" param, but for some reason this param isn't taken to account.

here is a request for example that should return only events from Business and Career topic (id:2):
https://api.meetup.com/find/upcoming_events?&sign=true&photo-host=public&topic_category=2&page=20&order=time

But the results contain other topics as well.
It doesn't matter how I play with it, the results are just ignoring this param.

Do I miss anything in my request?

**Comment by jkutianski** [comment]
Well, "Business and Career" is id: 522 at least at [https://secure.meetup.com/meetup_api/console/?path=/find/topic_categories](https://secure.meetup.com/meetup_api/console/?path=/find/topic_categories)
```
Meetup API can be shitty some times :) 
`23` as `key`, `522` as `id` and the last most confusing `category_ids` (List of numeric category ids associated with this topic category) with `2`

{
   "23": {
      "id": 522,
      "shortname": "career-business",
      "name": "Carrera y negocios",
      "sort_name": "Carrera y negocios",
      "photo": {
      "id": 450131927,
      "highres_link": "https://secure.meetupstatic.com/photos/event/2/e/9/7/highres_450131927.jpeg",
      "photo_link": "https://secure.meetupstatic.com/photos/event/2/e/9/7/600_450131927.jpeg",
      "thumb_link": "https://secure.meetupstatic.com/photos/event/2/e/9/7/thumb_450131927.jpeg",
      "type": "event",
      "base_url": "https://secure.meetupstatic.com"
   },
   "category_ids": [
     2
   ]
}
```
